fire_base:
  api_url: "https://fcm.googleapis.com/v1/projects/runwithme-357006/messages:send"
  firebase_config_path: "firebase/runwithme-357006-firebase-adminsdk-y9y1r-0f6323cdc2.json"
  scoped: "https://www.googleapis.com/auth/cloud-platform"
  
# https://fcm.googleapis.com/v1/projects/runwithme-357006/messages:send