spring:
  profiles:
    include:
    - oauth
    - aws
    - firebase
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  mail:
    host: smtp.gmail.com
    username: skj2393@gmail.com
    port: '587'
    password: sgjskj2393
  jpa:
    database: mysql
    properties:
      hibernate:
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/commonssafy?serverTimezone=UTC&characterEncoding=UTF-8
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
logging:
  level:
    org:
      hibernate: info
    root: info
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
server:
  servlet:
    context-path: /api
  port: '8080'
  